# Change these first
owner: pyromaniacals # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Pyrocy frontend
    url: https://pyrocy.cc
  - name: Pyrocy backend
    url: https://backend.pyrocy.cc

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://github.com/pyromaniacals/brand/blob/main/icons/pyrocy-icon.png?raw=true
  themeUrl: https://pyromaniacals.github.io/upptime/pyrocy.css
  name: Pyrocy Status
  introTitle: "**Pyrocy** Status"
  introMessage: View the current status of our infrastructure here
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER

skipDeleteIssues: true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
